#!/usr/bin/env bash
# transfers a file from our client to a server

if [ $# -lt 2 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP"
else
	scp -o StrictHostKeyChecking=no -i ~/.ssh/school "$1" "ubuntu@$2":~
fi
